FROM python:3.12-slim

WORKDIR /app
RUN pip install --no-cache-dir uv

COPY backend /app
RUN uv sync --no-dev

ENV PYTHONPATH=/app
EXPOSE 8000
CMD ["uv", "run", "uvicorn", "cmd.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
